import { Current } from "./Current/Current";
import { Forecast } from "./Forecast/Forecast";
import { SwitchBtn } from "./SwitchBtn/SwitchBtn";
import { Hourly } from "./Hourly/Hourly";
import { Daily } from "./Daily/Daily";
export { Current };
export { Forecast };
export { SwitchBtn };
export { Hourly };
export { Daily };
